# Generated by Django 5.0.3 on 2024-07-10 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='folded_players',
            field=models.ManyToManyField(related_name='folded_in_round', to=settings.AUTH_USER_MODEL),
        ),
    ]
