# Generated by Django 5.0.3 on 2024-07-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_gamestate_folded_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
    ]
