# Generated by Django 5.0.3 on 2024-07-11 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_round_is_over'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_balances', to='party.party')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_balances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
